sudo: required
services: 
  - docker

before install:
  - docker build -t joelp172/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true joelp172/docker-react npm run test

deploy:
  provide: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket-name: "elasticbeanstalk-eu-west-2-003190583953"
  bucket_path: "docker-react"
  on:
    branch: main
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY